"""add table to connection

Revision ID: 6493c239c218
Revises: cd0b4ea64cc4
Create Date: 2024-04-24 02:57:31.412375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6493c239c218'
down_revision: Union[str, None] = 'cd0b4ea64cc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection', sa.Column('table', sa.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connection', 'table')
    # ### end Alembic commands ###
