"""set version_id nullable

Revision ID: 4d693d9a8d87
Revises: 90d4f20374cb
Create Date: 2024-04-17 21:59:49.116375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d693d9a8d87'
down_revision: Union[str, None] = '90d4f20374cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job', 'version_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job', 'version_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
