"""add version_id to data_tmp

Revision ID: 222f277e24e9
Revises: cca1655f3051
Create Date: 2024-04-30 16:12:37.150970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '222f277e24e9'
down_revision: Union[str, None] = 'cca1655f3051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_tmp', sa.Column('version_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_data_tmp_version_id'), 'data_tmp', ['version_id'], unique=False)
    op.create_foreign_key(None, 'data_tmp', 'version', ['version_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data_tmp', type_='foreignkey')
    op.drop_index(op.f('ix_data_tmp_version_id'), table_name='data_tmp')
    op.drop_column('data_tmp', 'version_id')
    # ### end Alembic commands ###
