"""rename data_tmp

Revision ID: cca1655f3051
Revises: efe2f2b08ebe
Create Date: 2024-04-30 14:44:03.340853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cca1655f3051'
down_revision: Union[str, None] = 'efe2f2b08ebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_tmp',
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('datatmp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datatmp',
    sa.Column('field_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='datatmp_pkey')
    )
    op.drop_table('data_tmp')
    # ### end Alembic commands ###
