"""change version_id nullable

Revision ID: 7b28b23b73b6
Revises: e6097204a3c9
Create Date: 2024-03-27 02:23:01.592993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b28b23b73b6'
down_revision: Union[str, None] = 'e6097204a3c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job', 'version_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job', 'version_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
