"""rename data_pipeline to pipeline_id

Revision ID: 09979aaef7cf
Revises: 0f5d24b50f7d
Create Date: 2024-04-04 21:45:20.642918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09979aaef7cf'
down_revision: Union[str, None] = '0f5d24b50f7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection', sa.Column('pipeline_id', sa.UUID(), nullable=False))
    op.drop_index('ix_connection_data_pipeline', table_name='connection')
    op.create_index(op.f('ix_connection_pipeline_id'), 'connection', ['pipeline_id'], unique=False)
    op.drop_constraint('connection_data_pipeline_fkey', 'connection', type_='foreignkey')
    op.create_foreign_key(None, 'connection', 'data_pipeline', ['pipeline_id'], ['id'], ondelete='cascade')
    op.drop_column('connection', 'data_pipeline')
    op.add_column('field', sa.Column('pipeline_id', sa.UUID(), nullable=False))
    op.drop_index('ix_field_data_pipeline', table_name='field')
    op.create_index(op.f('ix_field_pipeline_id'), 'field', ['pipeline_id'], unique=False)
    op.drop_constraint('field_data_pipeline_fkey', 'field', type_='foreignkey')
    op.create_foreign_key(None, 'field', 'data_pipeline', ['pipeline_id'], ['id'], ondelete='cascade')
    op.drop_column('field', 'data_pipeline')
    op.add_column('file', sa.Column('pipeline_id', sa.UUID(), nullable=False))
    op.drop_index('ix_file_data_pipeline', table_name='file')
    op.create_index(op.f('ix_file_pipeline_id'), 'file', ['pipeline_id'], unique=False)
    op.drop_constraint('file_data_pipeline_fkey', 'file', type_='foreignkey')
    op.create_foreign_key(None, 'file', 'data_pipeline', ['pipeline_id'], ['id'], ondelete='cascade')
    op.drop_column('file', 'data_pipeline')
    op.add_column('job', sa.Column('pipeline_id', sa.UUID(), nullable=False))
    op.drop_index('ix_job_data_pipeline', table_name='job')
    op.create_index(op.f('ix_job_pipeline_id'), 'job', ['pipeline_id'], unique=False)
    op.drop_constraint('job_data_pipeline_fkey', 'job', type_='foreignkey')
    op.create_foreign_key(None, 'job', 'data_pipeline', ['pipeline_id'], ['id'], ondelete='cascade')
    op.drop_column('job', 'data_pipeline')
    op.add_column('link', sa.Column('pipeline_id', sa.UUID(), nullable=False))
    op.drop_index('ix_link_data_pipeline', table_name='link')
    op.create_index(op.f('ix_link_pipeline_id'), 'link', ['pipeline_id'], unique=False)
    op.drop_constraint('link_data_pipeline_fkey', 'link', type_='foreignkey')
    op.create_foreign_key(None, 'link', 'data_pipeline', ['pipeline_id'], ['id'], ondelete='cascade')
    op.drop_column('link', 'data_pipeline')
    op.add_column('log', sa.Column('pipeline_id', sa.UUID(), nullable=False))
    op.drop_index('ix_log_data_pipeline', table_name='log')
    op.create_index(op.f('ix_log_pipeline_id'), 'log', ['pipeline_id'], unique=False)
    op.drop_constraint('log_data_pipeline_fkey', 'log', type_='foreignkey')
    op.create_foreign_key(None, 'log', 'data_pipeline', ['pipeline_id'], ['id'], ondelete='cascade')
    op.drop_column('log', 'data_pipeline')
    op.add_column('running_job', sa.Column('pipeline_id', sa.UUID(), nullable=False))
    op.drop_index('ix_running_job_data_pipeline', table_name='running_job')
    op.create_index(op.f('ix_running_job_pipeline_id'), 'running_job', ['pipeline_id'], unique=False)
    op.drop_constraint('running_job_data_pipeline_fkey', 'running_job', type_='foreignkey')
    op.create_foreign_key(None, 'running_job', 'data_pipeline', ['pipeline_id'], ['id'], ondelete='cascade')
    op.drop_column('running_job', 'data_pipeline')
    op.add_column('version', sa.Column('pipeline_id', sa.UUID(), nullable=False))
    op.drop_index('ix_version_data_pipeline', table_name='version')
    op.create_index(op.f('ix_version_pipeline_id'), 'version', ['pipeline_id'], unique=False)
    op.drop_constraint('version_data_pipeline_fkey', 'version', type_='foreignkey')
    op.create_foreign_key(None, 'version', 'data_pipeline', ['pipeline_id'], ['id'], ondelete='cascade')
    op.drop_column('version', 'data_pipeline')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('version', sa.Column('data_pipeline', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'version', type_='foreignkey')
    op.create_foreign_key('version_data_pipeline_fkey', 'version', 'data_pipeline', ['data_pipeline'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_version_pipeline_id'), table_name='version')
    op.create_index('ix_version_data_pipeline', 'version', ['data_pipeline'], unique=False)
    op.drop_column('version', 'pipeline_id')
    op.add_column('running_job', sa.Column('data_pipeline', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'running_job', type_='foreignkey')
    op.create_foreign_key('running_job_data_pipeline_fkey', 'running_job', 'data_pipeline', ['data_pipeline'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_running_job_pipeline_id'), table_name='running_job')
    op.create_index('ix_running_job_data_pipeline', 'running_job', ['data_pipeline'], unique=False)
    op.drop_column('running_job', 'pipeline_id')
    op.add_column('log', sa.Column('data_pipeline', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'log', type_='foreignkey')
    op.create_foreign_key('log_data_pipeline_fkey', 'log', 'data_pipeline', ['data_pipeline'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_log_pipeline_id'), table_name='log')
    op.create_index('ix_log_data_pipeline', 'log', ['data_pipeline'], unique=False)
    op.drop_column('log', 'pipeline_id')
    op.add_column('link', sa.Column('data_pipeline', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'link', type_='foreignkey')
    op.create_foreign_key('link_data_pipeline_fkey', 'link', 'data_pipeline', ['data_pipeline'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_link_pipeline_id'), table_name='link')
    op.create_index('ix_link_data_pipeline', 'link', ['data_pipeline'], unique=False)
    op.drop_column('link', 'pipeline_id')
    op.add_column('job', sa.Column('data_pipeline', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.create_foreign_key('job_data_pipeline_fkey', 'job', 'data_pipeline', ['data_pipeline'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_job_pipeline_id'), table_name='job')
    op.create_index('ix_job_data_pipeline', 'job', ['data_pipeline'], unique=False)
    op.drop_column('job', 'pipeline_id')
    op.add_column('file', sa.Column('data_pipeline', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.create_foreign_key('file_data_pipeline_fkey', 'file', 'data_pipeline', ['data_pipeline'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_file_pipeline_id'), table_name='file')
    op.create_index('ix_file_data_pipeline', 'file', ['data_pipeline'], unique=False)
    op.drop_column('file', 'pipeline_id')
    op.add_column('field', sa.Column('data_pipeline', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'field', type_='foreignkey')
    op.create_foreign_key('field_data_pipeline_fkey', 'field', 'data_pipeline', ['data_pipeline'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_field_pipeline_id'), table_name='field')
    op.create_index('ix_field_data_pipeline', 'field', ['data_pipeline'], unique=False)
    op.drop_column('field', 'pipeline_id')
    op.add_column('connection', sa.Column('data_pipeline', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'connection', type_='foreignkey')
    op.create_foreign_key('connection_data_pipeline_fkey', 'connection', 'data_pipeline', ['data_pipeline'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_connection_pipeline_id'), table_name='connection')
    op.create_index('ix_connection_data_pipeline', 'connection', ['data_pipeline'], unique=False)
    op.drop_column('connection', 'pipeline_id')
    # ### end Alembic commands ###
