"""add field date for pipeline

Revision ID: 1061c01f553d
Revises: 09979aaef7cf
Create Date: 2024-04-11 20:40:04.675487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1061c01f553d'
down_revision: Union[str, None] = '09979aaef7cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_pipeline', sa.Column('date', sa.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_pipeline', 'date')
    # ### end Alembic commands ###
