"""add db_name to connection

Revision ID: 1a5774ffae6d
Revises: 999aa8bed040
Create Date: 2024-04-26 23:16:26.978084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a5774ffae6d'
down_revision: Union[str, None] = '999aa8bed040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection', sa.Column('db_name', sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connection', 'db_name')
    # ### end Alembic commands ###
