"""version id on delete set null in job

Revision ID: 15ca357368c2
Revises: 2873cfc6c399
Create Date: 2024-05-09 12:57:09.597278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15ca357368c2'
down_revision: Union[str, None] = '2873cfc6c399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('job_version_id_fkey', 'job', type_='foreignkey')
    op.create_foreign_key(None, 'job', 'version', ['version_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.create_foreign_key('job_version_id_fkey', 'job', 'version', ['version_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
