"""add date to log

Revision ID: 2873cfc6c399
Revises: c4ad83272bc0
Create Date: 2024-05-01 19:46:14.877604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2873cfc6c399'
down_revision: Union[str, None] = 'c4ad83272bc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log', sa.Column('date', sa.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log', 'date')
    # ### end Alembic commands ###
