"""add link field

Revision ID: 2018d4ff074b
Revises: 29340c3f225f
Create Date: 2024-03-27 21:07:28.841950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2018d4ff074b'
down_revision: Union[str, None] = '29340c3f225f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('data_pipeline', sa.UUID(), nullable=False),
    sa.Column('link', sa.VARCHAR(length=255), nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['data_pipeline'], ['data_pipeline.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_data_pipeline'), 'link', ['data_pipeline'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_link_data_pipeline'), table_name='link')
    op.drop_table('link')
    # ### end Alembic commands ###
