"""add schema to connection

Revision ID: 2e14dffac669
Revises: 1a5774ffae6d
Create Date: 2024-04-28 20:39:35.832423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e14dffac669'
down_revision: Union[str, None] = '1a5774ffae6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connection', sa.Column('schema', sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connection', 'schema')
    # ### end Alembic commands ###
