"""add data_tmp

Revision ID: efe2f2b08ebe
Revises: 2e14dffac669
Create Date: 2024-04-30 14:42:42.074876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efe2f2b08ebe'
down_revision: Union[str, None] = '2e14dffac669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datatmp',
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datatmp')
    # ### end Alembic commands ###
